language: php

php:
  - 5.6
  - 7.0
  - hhvm

install:
  - composer install -n

script: phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - vendor/bin/codacycoverage clover build/logs/clover.xml
  - vendor/bin/test-reporter
