language: php

php:
  - 5.6
  - 7.0
  - hhvm

install: composer install --dev --no-interaction

before_script:
  - |
    if [[ $TRAVIS_PHP_VERSION = "hhv"* ]]; then
      cat testphpconfig.ini >> /etc/hhvm/php.ini
    else
      phpenv config-add testphpconfig.ini
    fi

script: phpunit

after_success:
  # CodeClimate.com
  - vendor/bin/test-reporter
  # Codecov.io
  - bash <(curl -s https://codecov.io/bash)
  # Codacy.com
  - vendor/bin/codacycoverage clover build/logs/clover.xml
  # Coveralls.io
  - vendor/bin/phpcov.php merge --clover build/logs/clover.xml build/cov
  - vendor/bin/coveralls
