language: php

php:
  - 5.6
  - 7.0
  - hhvm

script: phpunit

before_script:
  - composer install -n

after_script:
  - bash <(curl -s https://codecov.io/bash)
  - vendor/bin/codacycoverage clover build/logs/clover.xml
  - vendor/bin/test-reporter
